apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app1
  template:
    metadata:
      labels:
        app: my-app1
    spec:
      containers:
        - name: my-container
          image: us-central1-docker.pkg.dev/dtonic-demo-k8s/gke-repo/quickstart-image
          ports:
            - containerPort: 8080

apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer

# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: flask-deployment
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: flask-app
#   template:
#     metadata:
#       labels:
#         app: flask-app
#     spec:
#       containers:
#         - name: flask-container
#           image: us-central1-docker.pkg.dev/dtonic-demo-k8s/gke-repo/flask-image
#           ports:
#             - containerPort: 8081

# apiVersion: v1
# kind: Service
# metadata:
#   name: flask-service
# spec:
#   selector:
#     app: flask-app
#   ports:
#     - protocol: TCP
#       port: 8081
#       targetPort: 8081
#   type: LoadBalancer